#!/usr/bin/env bash
set -euo pipefail

# Builds hashjunkie-wasm and generates the embedded TypeScript blob.
# Run whenever crates/hashjunkie-wasm or core hashing code changes.
#
# Prerequisites:
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-bindgen-cli --version 0.2.120
#   wasm-opt (optional): apt install binaryen / brew install binaryen

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_DIR="$REPO_ROOT/npm/hashjunkie"
CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export PATH="$CARGO_HOME/bin:$PATH"
WASM_RAW="$REPO_ROOT/target/wasm32-unknown-unknown/wasm-release/hashjunkie_wasm.wasm"

echo "==> Building hashjunkie-wasm..."
cargo build \
  --manifest-path "$REPO_ROOT/Cargo.toml" \
  -p hashjunkie-wasm \
  --target wasm32-unknown-unknown \
  --profile wasm-release

# Generate JS glue with wasm-bindgen --target web
TMPDIR_OUT=$(mktemp -d)
trap 'rm -rf "$TMPDIR_OUT"' EXIT
# --target web produces a self-contained ESM module that works in browsers and Bun
# without requiring a bundler step to handle .wasm imports.
echo "==> Running wasm-bindgen --target web..."
wasm-bindgen --target web --out-dir "$TMPDIR_OUT" "$WASM_RAW"

# Copy glue files into the npm package
cp "$TMPDIR_OUT/hashjunkie_wasm.js"   "$PKG_DIR/hashjunkie_wasm.js"
cp "$TMPDIR_OUT/hashjunkie_wasm.d.ts" "$PKG_DIR/hashjunkie_wasm.d.ts"

# Generate wasm_blob.ts — base64 of the .wasm binary
# Use portable python3 instead of base64 -w0 (macOS compat: base64 doesn't support -w)
BLOB=$(python3 -c "import base64,sys; sys.stdout.write(base64.b64encode(sys.stdin.buffer.read()).decode())" < "$TMPDIR_OUT/hashjunkie_wasm_bg.wasm")
cat > "$PKG_DIR/wasm_blob.ts" << TSEOF
// Generated by scripts/build-wasm.sh — do not edit manually.
// Regenerate when crates/hashjunkie-wasm or core hashing code changes:
//   ./scripts/build-wasm.sh
export const WASM_BLOB = "$BLOB";
TSEOF

echo "==> Done. Generated:"
echo "    $PKG_DIR/hashjunkie_wasm.js"
echo "    $PKG_DIR/hashjunkie_wasm.d.ts"
echo "    $PKG_DIR/wasm_blob.ts ($(wc -c < "$PKG_DIR/wasm_blob.ts") bytes)"
